# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions

name: Build and deploy to webapp-poc-dev

on:
  push:
    branches:
      - beta
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      
      - name: Get package version
        id: get_version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: Install Dependencies
        run: npm i
      
      - name: Build Back-office
        run: npx nx run back-office:build:${{ secrets.CONFIG }}
      
      - name: Build Front-office
        run: npx nx run front-office:build:${{ secrets.CONFIG }}
      
      - name: Archive build Back-office
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: back_office
          path: dist/apps/back-office
      
      - name: Archive build Front-office
        if: success()
        uses: actions/upload-artifact@v3
        with:
          name: front_office
          path: dist/apps/front-office

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v2
        with:
          name: node-app

      - name: 'Deploy to Azure Web App'
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v2
        with:
          app-name: 'webapp-poc-dev'
          slot-name: 'Production'
          publish-profile: ${{ secrets.AZUREAPPSERVICE_PUBLISHPROFILE_E736B0906FB64895B696940B8547F64D }}
          package: .
