name: CI

on:
  push:
    branches:
      - main
      - next
      - next-major
      - beta
      - alpha

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - name: Cache node modules
        uses: actions/cache@v3
        with:
          path: node_modules
          key: ${{ runner.OS }}-build-${{ hashFiles('**/package-lock.json') }}
          restore-keys: |
            ${{ runner.OS }}-build-${{ env.cache-name }}-
            ${{ runner.OS }}-build-
            ${{ runner.OS }}-
      - name: Install Dependencies
        run: npm i
      - name: Build Shared Library ( < 2.0 )
        run: npm run build -- --configuration=production safe
        if: github.ref != 'beta' && github.ref != 'alpha'
      - name: Build Back-office ( < 2.0 )
        run: npm run build -- --configuration=azure-uat back-office
        if: github.ref != 'beta' && github.ref != 'alpha'
      - name: Build Front-office ( < 2.0 )
        run: npm run build -- --configuration=azure-uat front-office
        if: github.ref != 'beta' && github.ref != 'alpha'
      - name: Build Back-office ( >= 2.0 )
        run: npx nx run back-office:build:azure-uat
        if: github.ref == 'beta' || github.ref == 'alpha'
      - name: Build Front-office ( >= 2.0 )
        run: npx nx run front-office:build:azure-uat
        if: github.ref == 'beta' || github.ref == 'alpha'

  release:
    name: Release
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 'lts/*'
      - name: Install dependencies
        run: npm ci
      - name: Release
        env:
          GITHUB_TOKEN: ${{ secrets.SEMANTIC_RELEASE_TOKEN }}
        run: npx semantic-release
